### PR TITLE
V3.0.0 Release

### PR DESCRIPTION
**Pull request by vivchar**
* #44 wrap RecyclerView to WeakReference enhancement ;
* #42 add setOnClickListener without View paramenter enhancement;
* #38 add CustomViewFinder support enhancement;
* #32 migration to ListAdapter enhancement;
* #15 ViewState not working as expected bug;
* #47 ViewState overrides value from Model;
* remove ViewRenderer;
* rename ViewBinder to ViewRenderer.

### CODE REVIEW

**Comment by vivchar** [comment]
```
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }

dependencies {
    compile 'com.github.vivchar:RendererRecyclerViewAdapter:3.0.0-SNAPSHOT'
}
```

**Comment by ivorsmorenburg** [comment]
When is  this PR going to be merged?

**Comment by vivchar** [comment]
@ivorsliide currently it is in testing, you can try this via 
```
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }

dependencies {
    compile 'com.github.vivchar:RendererRecyclerViewAdapter:3.0.0-SNAPSHOT'
}
```

**Comment by ivorsmorenburg** [comment]
I had access forbidden, I'll try again anyway, thanks. And great library

**Comment by vivchar** [comment]
@ivorsliide thank you! 
>had access forbidden

It is correct behaviour when you try open https://oss.sonatype.org/content/repositories/snapshots/ in browser.
You should add this url in your main `build.gradle` in the repository section:
```
allprojects {
	repositories {
		google()
		jcenter()
		maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
	}
}
```
Then you will have ability to use 
```
dependencies {
    compile 'com.github.vivchar:RendererRecyclerViewAdapter:3.0.0-SNAPSHOT'
}
```
Or use full url to see
https://oss.sonatype.org/content/repositories/snapshots/com/github/vivchar/RendererRecyclerViewAdapter/

**Review by ivorsmorenburg — APPROVED** [review]

**Comment by ivorsmorenburg** [comment]
Should we merge?

**Comment by vivchar** [comment]
@ivorsliide yes, we should merge it, but currently I have no time to prepare new version. I believe I will do in in few weeks.

**Pull request merged**
